import type { SongPackage, User } from "./types";

export const DENNIS = {
  id: "c-dennis",
  name: "Dennis Lau",
  title: "Violinist · Producer · Your Songwriter",
  city: "Kuala Lumpur",
  image: "/artists/dennis-lau.jpg",
  imageAlt: "Dennis Lau portrait",
  bio: "Dennis Lau is Malaysia's electric violin maestro — a classically trained rebel who has turned stages from Kuala Lumpur to London into singalongs. On Blesspoke, he is the only artist. Every song is his hand, his bow, his production — made for one person only: you.",
  longBio:
    "Dennis Lau has spent two decades bending the violin into shapes nobody expected — EDM anthems, wedding waltzes, film scores, stadium rock. He has performed across Asia and Europe, collaborated with orchestras and DJs alike, and built Blesspoke on a single belief: a song made for you should belong to you.",
};

export const PACKAGES: SongPackage[] = [
  {
    id: "pkg-signature",
    kind: "signature",
    name: "Signature",
    tier: "The Essential",
    price: 499,
    currency: "USD",
    days: 7,
    revisions: 2,
    blurb: "A bespoke song written from your single prompt. Acoustic heart, Dennis's signature violin.",
    includes: [
      "One original song (2–3 min)",
      "Written from your prompt",
      "Dennis on violin + vocals",
      "2 revision rounds",
      "Full ownership deed",
      "Studio-mastered files",
    ],
  },
  {
    id: "pkg-story",
    kind: "story",
    name: "Story",
    tier: "The Bestseller",
    price: 1299,
    currency: "USD",
    days: 10,
    revisions: 3,
    blurb: "A full production piece — layered strings, keys, and arrangement built around your story.",
    includes: [
      "One original song (3–4 min)",
      "Full production arrangement",
      "Live string ensemble layers",
      "3 revision rounds",
      "Full ownership deed",
      "Stems + mastered files",
      "Lyric sheet, signed",
    ],
    featured: true,
  },
  {
    id: "pkg-anthem",
    kind: "anthem",
    name: "Anthem",
    tier: "The Grand Gesture",
    price: 3900,
    currency: "USD",
    days: 14,
    revisions: 4,
    blurb: "The flagship. A cinematic anthem with orchestra-grade production — and a private video dedication from Dennis.",
    includes: [
      "One original anthem (4+ min)",
      "Orchestra-grade production",
      "Live session musicians",
      "4 revision rounds",
      "Full ownership deed",
      "Stems, masters, instrumentals",
      "Private video dedication",
      "Hand-signed certificate",
    ],
  },
];

export const DEMO_USERS: User[] = [
  {
    id: "u-listener",
    email: "you@blesspoke.com",
    password: "demo",
    name: "Aisha Rahman",
    role: "listener",
    phone: "+60 12-345 6789",
    createdAt: "2026-01-12",
    emailVerified: true,
    is2fa: false,
    status: "active",
  },
  {
    id: "u-dennis",
    email: "dennis@blesspoke.com",
    password: "demo",
    name: "Dennis Lau",
    role: "creator",
    phone: "+60 16-888 1234",
    createdAt: "2025-11-01",
    emailVerified: true,
    is2fa: true,
    status: "active",
  },
  {
    id: "u-admin",
    email: "admin@lumo.gg",
    password: "demo",
    name: "Lumo Operator",
    role: "admin",
    phone: "+60 17-000 1111",
    createdAt: "2025-10-01",
    emailVerified: true,
    is2fa: true,
    status: "active",
  },
];

export const OCCASIONS = [
  "Wedding",
  "Proposal",
  "Anniversary",
  "Birthday",
  "Farewell",
  "Newborn",
  "Graduation",
  "Just because",
  "Brand anthem",
  "Memorial",
];
