import type { CSSProperties } from "react";

/**
 * One grain layer, mounted once per concept.
 *
 * The noise is generated by the browser from an inline SVG filter rather than
 * fetched, so it costs nothing and cannot go missing. Concepts set their own
 * opacity and blend mode: lacquer wants a little, silk wants very little, paper
 * wants it multiplied rather than overlaid so it reads as tooth in the sheet.
 */

const NOISE =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.86' numOctaves='3' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23n)' opacity='0.55'/%3E%3C/svg%3E\")";

export function Grain() {
  return <div className="grain" style={{ "--grain-image": NOISE } as CSSProperties} aria-hidden />;
}
